# Generated by Django 3.2.19 on 2023-12-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='author',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='created_on',
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='Anonymous', max_length=80),
        ),
        migrations.AddField(
            model_name='submission',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='blog.post'),
        ),
    ]
